### ISSUE TITLE
Invisible input text at prompt on ubuntu with lightyellow background theme

### ISSUE THREAD

**Issue by ivarne** [Keno/REPL.jl#13]
I tried the new REPL, but I have some problems when I use my default color theme with light yellow background. I can use Julia normally, but not see the text I write nor the completions.

I think this has something to do with `repl.input_color` being the same as the background color, but I can not figure out where it is set or how to change it.

**Comment by Keno** [comment]
Colors are currently hardcoded here: https://github.com/loladiro/REPL.jl/blob/master/src/REPL.jl#L140.
Can you try changing that and if that works, we can make it configurable.

**Comment by ivarne** [comment]
Aha, You hardcode `Base.text_colors[:white]` as the `input_color`. That is definitely a problem for those of us who prefer a light background on the terminal. When I change it to `Base.text_colors[:normal]`, things gets much better. Both on dark and light background.
