### ISSUE TITLE
Suppress output if input ends with a ;

### ISSUE THREAD

**Issue by ViralBShah** [Keno/REPL.jl#18]
The ';' is ignored currently, instead of suppressing output:

```
julia> a = rand(5);
5-element Array{Float64,1}:
 0.682671
 0.14447 
 0.228063
 0.984556
 0.524574
```

**Comment by Keno** [comment]
Good catch!

**Comment by carlobaldassi** [comment]
Very minor point (which actually also happens in julia's own REPL): semicolons are now effective at suppressing output also within comments in certain cases, e.g. if placed at the end:

```
julia> 123 #
123

julia> 123 #;

julia> 123 #;1
123

julia> 123 #; #

julia> 123 #; #123

julia>
```

I suppose everything in comments should just be ignored.
