### ISSUE TITLE
multiline ctrl-A/E behavior

### ISSUE THREAD

**Issue by StefanKarpinski** [Keno/REPL.jl#21]
This is a slight behavioral incompatibility which is up for debate. In the C REPL, the first time you do ctrl-A, in a multiline input, it sends you to the start of the _current_ line; the second time it sends you to the beginning of the entire input. Likewise for ctrl-E. I rather like this behavior (no surprise since I implemented it), but thought I'd bring it up here.

**Comment by Keno** [comment]
Fixed.

**Comment by StefanKarpinski** [comment]
Thanks! Now it's perfect.
