### ISSUE TITLE
Ctrl+enter ignored (behaves as plain enter)

### ISSUE THREAD

**Issue by carlobaldassi** [Keno/REPL.jl#24]
as per the subject; this prevents e.g. editing multi-line commands by inserting a new line.

**Comment by StefanKarpinski** [comment]
It took me a moment to figure out that this was a feature request, not a bug report.

**Comment by carlobaldassi** [comment]
Ops, no, it is a bug report, but it maybe got fixed in the last few hours? I just updated and the problem is gone. Closing.
