### ISSUE TITLE
interaction bewteen shell mode and full-screen programs

### ISSUE THREAD

**Issue by StefanKarpinski** [Keno/REPL.jl#27]
When I do `;less /usr/share/dict/words` for example, bad things happen. The `julia` REPL process gets a `SIGHUP` (or something) that was meant for the `less` process and ends up sleeping, dumping me into the outer shell that I started `julia` from. This is why the C repl does the `$shell -c "($cmd) && true"` business – or is this a different issue?

**Comment by Keno** [comment]
I'll have a look.

**Comment by Keno** [comment]
Fixed!

**Comment by StefanKarpinski** [comment]
Dude. You're amazing.
