### ISSUE TITLE
History does not remember type of command.

### ISSUE THREAD

**Issue by ivarne** [Keno/REPL.jl#30]
The discussion in https://github.com/loladiro/REPL.jl/issues/29 started off a little wrong, so I open a new Issue for the relevant part.

When browsing trough history, the new REPL does not remember if the command was a `julia>`, `help>` or `shell>` command. This is annoying, especially for shell commands, because it makes no sense to run a shell command in Julia.

**Comment by Keno** [comment]
Yep, will change.

**Comment by Keno** [comment]
Done

**Comment by ivarne** [comment]
Thanks now it is almost there.

If I go back in history, I can not remove the `shell>` prompt with backspace. The following keypresses illustrates the issue on my Ubuntu machine.

```
;ls[ enter ][ arrow up ][ arrow left ][ arrow left ][ backspace ]
```

**Comment by StefanKarpinski** [comment]
Yeah, this is why I was thinking that it made sense to leave the prefix there but not show it.
