### ISSUE TITLE
weird issues with enter

### ISSUE THREAD

**Issue by StefanKarpinski** [Keno/REPL.jl#31]
I initially noticed this with shell mode and commands ending with `.` but it seems to happen more often. Sometimes the REPL just gets confused and doesn't seem to recognize `enter`. E.g.:

``` julia
shell> echo .


.
```

Which is what it looks like – me typing `echo .` and hitting enter several times before the input is evaluated. There are other situations where this kind of thing happens too though.

**Comment by StefanKarpinski** [comment]
I don't think this is a code compilation delay or anything – waiting arbitrarily long after hitting enter the first time doesn't do anything.

**Comment by Keno** [comment]
Ah, maybe it's accidentally applying the julia command completion logic in shell mode.
