### ISSUE TITLE
Copy-paste multiple lines at once

### ISSUE THREAD

**Issue by johnmyleswhite** [Keno/REPL.jl#35]
I just started using this REPL today. I've found that this new REPL handles the copy-pasting of multiple lines at once differently from the old readline REPL.

If I copy and paste several lines at once in the end REPL, each line gets executed separately, which means that I see output from each line.

In this REPL, the whole chunk of text gets processed at once, so that I only get output from the last line. I can attach an image of a simple comparison if this description is unclear.

**Comment by Keno** [comment]
I thought this was a good idea when I first implemented it, but turns out in practice I don't really like it, so I will change it.

**Comment by johnmyleswhite** [comment]
Great. That's really the only thing I've hit with this REPL that seemed questionable in a few weeks of using it.
