### ISSUE TITLE
problems with multiple uses of include

### ISSUE THREAD

**Issue by EthanAnderes** [Keno/REPL.jl#39]
If I call include on a file multiple times I get an error. Here is an example:

julia> include("test1.jl")
3

julia> include("test1.jl")
ERROR: could not open file /Users/ethananderes/.julia/v0.3/REPL/scripts/test1.jl

**Comment by Keno** [comment]
Yes, I have noticed this too. Something seems to have changed WRT task local storage.

**Comment by EthanAnderes** [comment]
Ok. Glad to hear it's repeatable.  I was a bit worried it was a problem with my system. 

..nice work by the way. Can't wait till it's in base
